apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-local-repo
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
