apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-docker-pipeline
  namespace: infra
spec:
  description: |
    This pipeline checkout a Git repository, builds a Docker image from it, and pushes the built image to a container registry.
  params:
  - name: repo-url
    type: string
  - name: context-dir
    type: string
    default: '.'
    description: >-
      The directory from which to launch the Maven build
  - name: image-name
  workspaces:
  - name: source
  - name: maven-settings
  - name: maven-local-repo
  - name: docker-config
  tasks:
  - name: clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: $(params.repo-url)
  - name: package
    runAfter:
      - clone
    taskRef:
      kind: Task
      name: maven
    workspaces:
      - name: maven-settings
        workspace: maven-settings
      - name: source
        workspace: source
      - name: maven-local-repo
        workspace: maven-local-repo
    params:
    - name: GOALS
      value:
        - '-pl'
        - $(params.context-dir)
        - '-B'
        - clean
        - package
  - name: docker-build
    runAfter:
      - package
    taskRef:
      name: kaniko
    workspaces:
      - name: source
        workspace: source
      - name: dockerconfig
        workspace: docker-config
    params:
      - name: CONTEXT
        value: $(params.context-dir)
      - name: IMAGE
        value: $(params.image-name)
      # - name: STORAGE_DRIVER
      #   value: "$(params.storageDriver)"
      - name: TLSVERIFY
        value: 'false'
