apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-account
  namespace: infra

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-role
  namespace: infra
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - deployments
      - services
      - secrets
      - serviceaccounts
      - replicasets
    verbs: 
      - get
      - create
      - update
      - patch
      - list
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
  namespace: infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
  - kind: ServiceAccount
    name: pipeline-account
    namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipeline
rules:
  - apiGroups:
      - "source.toolkit.fluxcd.io"
    resources:
      - gitrepositories
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline-account
    namespace: infra
