apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline
  namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipeline
rules:
  - apiGroups:
      - "source.toolkit.fluxcd.io"
    resources:
      - gitrepositories
    verbs:
      - get
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - create
      - get
      - patch
  - apiGroups:
      - "apps"
    resources:
      - replicasets
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
      - serviceaccounts
    verbs:
      - get
      - create
      - update
      - patch
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-pipeline
subjects:
  - kind: ServiceAccount
    name: tekton-pipeline
    namespace: infra
