apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-repo-name
  namespace: infra
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Deployment
    tekton.dev/tags: git
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    This task will extract the repostory name from the provided Git repository URL.

  params:
    - name: url
    - name: image
      default: "docker.io/alpine:3.20.1"
  results:
    - name: repo-name
  steps:
    - name: extract
      image: $(params.image)
      script: |
        url=$(params.url)
        repo_name=${url##*/}
        repo_name=${repo_name%.*}
        printf "The repository name extracted from '%s' is '%s'" $(params.url) "${repo_name}"
        printf "%s" "${repo_name}" > "$(results.repo-name.path)"
