apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-chart-update
  namespace: infra
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Developer Tools
    tekton.dev/tags: yq
    tekton.dev/displayName: "YQ"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task will update the values used in the specified Helm chart. In particular, the image repository and tag will be updated.

  params:
    - name: repository
    - name: tag
    - name: chart-dir
      default: "."
    - name: environment
      default: ""
    - name: image
      default: linuxserver/yq:3.4.3
  workspaces:
    - name: source
  results:
    - name: previous-repository
    - name: previous-tag
    - name: current-repository
    - name: current-tag
    - name: values-file
  steps:
    - name: update
      image: $(params.image)
      workingDir: $(workspaces.source.path)/$(params.chart-dir)
      script: |
        repository=$(params.repository)
        tag=$(params.tag)
        environment=$(params.environment)

        if [ -n "${environment}" ] && [ "${environment}" != "local" ]; then
          values_file=values."${environment}".yaml
          if [[ ! -f "${values_file}" ]]; then
            cp values.yaml "${values_file}"
          fi
        else
          values_file="values.yaml"
        fi

        previous_repository=$(yq .image.repository "${values_file}")
        previous_tag=$(yq .image.tag "${values_file}")

        yq -y -i '(.image.repository = "'"${repository}"'") | (.image.tag = "'"${tag}"'")' "${values_file}"

        printf "${previous_repository}" | tr -d \" > $(results.previous-repository.path)
        printf "${previous_tag}" | tr -d \" > $(results.previous-tag.path)

        printf "${repository}" | tr -d \" > $(results.current-repository.path)
        printf "${tag}" | tr -d \" > $(results.current-tag.path)
        
        printf "${values_file}" | tr -d \" > $(results.values-file.path)
