apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mvn
  namespace: infra
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    This Task can be used to run a Maven build. It optimizes builds by using a local Maven repository passed in as a workspace.
  params:
  - name: maven-image
    default: gcr.io/cloud-builders/mvn:3.9.1
  - name: goals
    description: The Maven goals to run
    type: array
    default: ["package"]
  workspaces:
  - name: source
  - name: maven-local-repo
  - name: maven-settings
  steps:
    - name: mvn
      image: $(params.maven-image)
      workingDir: $(workspaces.source.path)
      command: ["/usr/bin/mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-local-repo.path)
        - -s
        - $(workspaces.maven-settings.path)/settings.xml
        - "$(inputs.params.goals)"
